# Generated by Django 5.2.12 on 2026-07-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chrono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='예: ediacaran-cambrian/bowyer2022-modelAB', unique=True)),
                ('scope', models.CharField(choices=[('boundary', 'boundary'), ('global', 'global (다경계 동시)')], default='boundary', max_length=10)),
                ('kind', models.CharField(help_text='예: global-d13C-age-model, committee-decision', max_length=100)),
                ('method', models.CharField(choices=[('decreed', 'decreed (GSSA)'), ('local-interpolation', 'local interpolation'), ('cross-section-correlation', 'cross-section correlation')], max_length=28)),
                ('provenance_ref', models.CharField(blank=True, help_text='값을 내는 서브그래프 참조', max_length=300)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('pin', 'pin'), ('range', 'range'), ('order', 'order'), ('freeze-version', 'freeze-version')], max_length=16)),
                ('value', models.JSONField(blank=True, default=dict, help_text='pin=값 / range=[min,max] / order=이웃 / freeze=버전')),
                ('rationale', models.TextField(blank=True)),
                ('ratified_year', models.IntegerField(blank=True, null=True)),
                ('overridable_in_sandbox', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clamps', to='chrono.authority')),
                ('target_boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clamps', to='chrono.boundary')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='예: ICC-2024/12', max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='chrono.authority')),
                ('clamps', models.ManyToManyField(blank=True, related_name='releases', to='releases.clamp')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.JSONField(help_text='Distribution.to_dict (nodes.distribution)')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_outputs', to='chrono.boundary')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='releases.modelcandidate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'boundary'), name='uniq_output_per_candidate_boundary')],
            },
        ),
        migrations.CreateModel(
            name='BoundaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_type', models.CharField(blank=True, max_length=8)),
                ('value_ma', models.FloatField(blank=True, null=True)),
                ('uncertainty', models.JSONField(blank=True, help_text='Distribution.to_dict', null=True)),
                ('method', models.CharField(blank=True, choices=[('decreed', 'decreed (GSSA)'), ('local-interpolation', 'local interpolation'), ('cross-section-correlation', 'cross-section correlation')], max_length=28)),
                ('provenance_ref', models.CharField(blank=True, max_length=300)),
                ('narrative', models.TextField(blank=True, help_text='GTS narrate 서술(스텁)')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='chrono.boundary')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='releases.modelcandidate')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='releases.release')),
            ],
            options={
                'ordering': ['boundary__slug'],
                'constraints': [models.UniqueConstraint(fields=('release', 'boundary'), name='uniq_record_per_release_boundary')],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='chrono.boundary')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='releases.modelcandidate')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='releases.release')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release', 'boundary'), name='uniq_selection_per_release_boundary')],
            },
        ),
    ]
