# Generated by Django 5.2.12 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='공표 기준 릴리스(Science CI 의 diff 대상). 그래프-bake 를 이것과 비교.'),
        ),
    ]
