# Generated by Django 5.2.12 on 2026-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_is_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryrecord',
            name='narrative',
            field=models.TextField(blank=True, help_text='GTS narrate prose (stub)'),
        ),
        migrations.AlterField(
            model_name='clamp',
            name='value',
            field=models.JSONField(blank=True, default=dict, help_text='pin=value / range=[min,max] / order=neighbors / freeze=version'),
        ),
        migrations.AlterField(
            model_name='modelcandidate',
            name='kind',
            field=models.CharField(help_text='e.g. global-d13C-age-model, committee-decision', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcandidate',
            name='provenance_ref',
            field=models.CharField(blank=True, help_text='Reference to the subgraph that produces the value', max_length=300),
        ),
        migrations.AlterField(
            model_name='modelcandidate',
            name='scope',
            field=models.CharField(choices=[('boundary', 'boundary'), ('global', 'global (multiple boundaries at once)')], default='boundary', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelcandidate',
            name='slug',
            field=models.SlugField(help_text='e.g. ediacaran-cambrian/bowyer2022-modelAB', unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='Published baseline release (the diff target of Science CI). Graph bakes are compared against this.'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(help_text='e.g. ICC-2024/12', max_length=50, unique=True),
        ),
    ]
