# Generated by Django 5.2.12 on 2026-07-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_alter_graph_options'),
        ('releases', '0003_alter_boundaryrecord_narrative_alter_clamp_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-created_at', 'version']},
        ),
        migrations.AddField(
            model_name='release',
            name='kind',
            field=models.CharField(choices=[('published', 'published'), ('bake', 'bake'), ('transient', 'transient')], default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='release',
            name='source_graph',
            field=models.ForeignKey(blank=True, help_text='Provenance: the graph this artifact was baked from (bake/transient kinds).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakes', to='graph.graph'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(help_text='e.g. ICC-2024/12 · GeologicTimeScale.Release.YYYYMMDD.NN', max_length=80, unique=True),
        ),
    ]
