# Generated by Django 5.2.12 on 2026-07-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_backfill_release_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who baked this artifact (null = system/published).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(help_text='e.g. ICC-2024/12 · GeologicTimeScale.Release.<user>.YYYYMMDD.NN', max_length=100, unique=True),
        ),
    ]
