# Generated by Django 5.2.12 on 2026-07-07 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_graph_forked_from'),
        ('releases', '0006_release_owner_alter_release_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'open'), ('merged', 'merged'), ('rejected', 'rejected')], default='open', max_length=8)),
                ('comment', models.TextField(blank=True)),
                ('affected', models.JSONField(blank=True, default=list, help_text='Boundary slugs the change moves/retypes (from the diff).')),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_against', to='releases.release')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='graph.graph')),
                ('result_release', models.ForeignKey(blank=True, help_text='The published Release baked when this proposal was ratified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_proposal', to='releases.release')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
