# Generated by Django 5.2.12 on 2026-07-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='base',
            field=models.ForeignKey(blank=True, help_text='The baseline this sandbox derives from (sandbox kind = base + per-boundary overrides).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandboxes', to='releases.release'),
        ),
        migrations.AlterField(
            model_name='release',
            name='kind',
            field=models.CharField(choices=[('published', 'published'), ('bake', 'bake'), ('sandbox', 'sandbox'), ('transient', 'transient')], default='published', max_length=12),
        ),
    ]
