# Generated by Django 5.2.12 on 2026-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0008_release_base_alter_release_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundaryrecord',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='Contributing reference slugs — cite-edge provenance snapshot at bake.'),
        ),
    ]
