# Generated by Django 5.2.12 on 2026-07-03 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chrono', '0001_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('sandbox', 'Sandbox'), ('proposed', 'Proposed'), ('ratified', 'Ratified'), ('deprecated', 'Deprecated')], default='sandbox', max_length=12)),
                ('viewport', models.JSONField(blank=True, default=dict, help_text='React Flow {x, y, zoom}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('collapsed', models.BooleanField(default=False)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='graph.graph')),
            ],
        ),
        migrations.CreateModel(
            name='NodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='React Flow 노드 id (그래프 내 유일)', max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graph.graph')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='graph.nodegroup')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='nodes.nodetype')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('output_port', models.CharField(default='out', max_length=100)),
                ('boundary', models.ForeignKey(blank=True, help_text='이 게이트웨이가 추정하는 경계(있으면)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='chrono.boundary')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='graph.graph')),
                ('node', models.ForeignKey(help_text='출력을 노출하는 노드', on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='graph.nodeinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_port', models.CharField(max_length=100)),
                ('target_port', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('data', 'data'), ('co-location', 'co-location'), ('calibration-transfer', 'calibration-transfer')], default='data', max_length=24)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='graph.graph')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='graph.nodeinstance')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='graph.nodeinstance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nodegroup',
            constraint=models.UniqueConstraint(fields=('graph', 'key'), name='uniq_group_key_per_graph'),
        ),
        migrations.AddConstraint(
            model_name='nodeinstance',
            constraint=models.UniqueConstraint(fields=('graph', 'key'), name='uniq_node_key_per_graph'),
        ),
        migrations.AddConstraint(
            model_name='gateway',
            constraint=models.UniqueConstraint(fields=('graph', 'slug'), name='uniq_gateway_slug_per_graph'),
        ),
    ]
