# Generated by Django 5.2.12 on 2026-07-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinstance',
            name='description',
            field=models.TextField(blank=True, help_text='사용자 설명(제목은 짧게, 상세는 여기 · 노드 툴팁). params 의 note 와 별개.'),
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='width',
            field=models.FloatField(blank=True, help_text='사용자가 조정한 노드 폭(px). null=기본 폭.', null=True),
        ),
    ]
