# Generated by Django 5.2.12 on 2026-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_nodeinstance_description_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodegroup',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
