# Generated by Django 5.2.12 on 2026-07-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_nodegroup_x_nodegroup_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodegroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='상위 그룹(중첩). null=최상위. 엔진 무관 — 표현/드릴인 계층만.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graph.nodegroup'),
        ),
    ]
