# Generated by Django 5.2.12 on 2026-07-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0003_alter_unit_rank'),
        ('graph', '0004_nodegroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodegroup',
            name='kind',
            field=models.CharField(choices=[('container', 'Container (표현용 묶음)'), ('unit', 'Unit (연대층서 구간 / span)')], default='container', help_text='그룹 성격. unit=연대층서 구간(span) — unit/lower/upper 로 정본 단위·경계 참조.', max_length=12),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='lower',
            field=models.ForeignKey(blank=True, help_text='아래(더 오래된) bounding 경계 노드. 인접/하위 그룹과 공유 가능.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lower_of_groups', to='graph.nodeinstance'),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='이 span 그룹이 표현하는 정본 단위(있으면). rank·이중명명 상속.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='span_groups', to='chrono.unit'),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='upper',
            field=models.ForeignKey(blank=True, help_text='위(더 젊은) bounding 경계 노드. 인접/상위 그룹과 공유 가능.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper_of_groups', to='graph.nodeinstance'),
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='nature',
            field=models.CharField(choices=[('generic', 'Generic (data/process/clamp 기계장치)'), ('boundary', 'Boundary (경계 점 / 0-셀 · 독립 시민)')], default='generic', help_text='노드 성격. boundary=경계 점(0-셀) — 독립 시민, 그룹에 담기지 않고 lower/upper 로 참조됨. node_type 과 직교.', max_length=12),
        ),
        migrations.AlterField(
            model_name='edge',
            name='kind',
            field=models.CharField(choices=[('data', 'data'), ('co-location', 'co-location'), ('calibration-transfer', 'calibration-transfer'), ('order', 'order')], default='data', max_length=24),
        ),
    ]
