# Generated by Django 5.2.12 on 2026-07-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0004_alter_authority_parent_alter_boundary_above_and_more'),
        ('graph', '0005_nodegroup_kind_nodegroup_lower_nodegroup_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='boundary',
            field=models.ForeignKey(blank=True, help_text='The boundary this gateway estimates (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='chrono.boundary'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='node',
            field=models.ForeignKey(help_text='The node whose output is exposed', on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='graph.nodeinstance'),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='kind',
            field=models.CharField(choices=[('container', 'Container (presentation grouping)'), ('unit', 'Unit (chronostratigraphic span)')], default='container', help_text='Group nature. unit=chronostratigraphic span — references the canonical unit/boundaries via unit/lower/upper.', max_length=12),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='lower',
            field=models.ForeignKey(blank=True, help_text='Lower (older) bounding boundary node. Can be shared with adjacent/child groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lower_of_groups', to='graph.nodeinstance'),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent group (nesting). null=top-level. Engine-agnostic — presentation/drill-in hierarchy only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graph.nodegroup'),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Canonical unit this span group represents (if any). Inherits rank and dual naming.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='span_groups', to='chrono.unit'),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='upper',
            field=models.ForeignKey(blank=True, help_text='Upper (younger) bounding boundary node. Can be shared with adjacent/parent groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper_of_groups', to='graph.nodeinstance'),
        ),
        migrations.AlterField(
            model_name='nodeinstance',
            name='description',
            field=models.TextField(blank=True, help_text='User description (keep the title short, put detail here · node tooltip). Separate from the note in params.'),
        ),
        migrations.AlterField(
            model_name='nodeinstance',
            name='key',
            field=models.CharField(help_text='React Flow node id (unique within the graph)', max_length=100),
        ),
        migrations.AlterField(
            model_name='nodeinstance',
            name='nature',
            field=models.CharField(choices=[('generic', 'Generic (data/process/clamp machinery)'), ('boundary', 'Boundary (boundary point / 0-cell · independent citizen)')], default='generic', help_text='Node nature. boundary=boundary point (0-cell) — independent citizen, not contained in a group but referenced via lower/upper. Orthogonal to node_type.', max_length=12),
        ),
        migrations.AlterField(
            model_name='nodeinstance',
            name='width',
            field=models.FloatField(blank=True, help_text='User-adjusted node width (px). null=default width.', null=True),
        ),
    ]
