# Generated by Django 5.2.12 on 2026-07-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_alter_gateway_boundary_alter_gateway_node_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['name']},
        ),
    ]
