# Generated by Django 5.2.12 on 2026-07-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_alter_graph_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text='The graph this was forked from (lineage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='graph.graph'),
        ),
    ]
