# Generated by Django 5.2.12 on 2026-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_graph_forked_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Free-text notes about this graph/branch.'),
        ),
    ]
