# Generated by Django 5.2.12 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_graph_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='kind',
            field=models.CharField(choices=[('data', 'data'), ('co-location', 'co-location'), ('calibration-transfer', 'calibration-transfer'), ('order', 'order'), ('cite', 'cite')], default='data', max_length=24),
        ),
    ]
