# Generated by Django 5.2.12 on 2026-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_alter_edge_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinstance',
            name='nature',
            field=models.CharField(choices=[('generic', 'Generic (data/process machinery)'), ('boundary', 'Boundary (boundary point / 0-cell · independent citizen)')], default='generic', help_text='Node nature. boundary=boundary point (0-cell) — independent citizen, not contained in a group but referenced via lower/upper. Orthogonal to node_type.', max_length=12),
        ),
    ]
