# Generated by Django 5.2.12 on 2026-07-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='안정 슬러그. 예: base-triassic', unique=True)),
                ('name', models.CharField(help_text='사람용 이름. 예: Base of the Triassic', max_length=200)),
                ('definition_type', models.CharField(blank=True, choices=[('GSSP', 'GSSP (지점)'), ('GSSA', 'GSSA (결정 숫자)')], help_text='현재 정의 방식. 버전별 진실은 releases 스냅샷.', max_length=8, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'boundaries',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('ICS', 'ICS'), ('subcommission', 'Subcommission'), ('sandbox-branch', 'Sandbox branch'), ('fork', 'Fork')], default='ICS', max_length=20)),
                ('parent', models.ForeignKey(blank=True, help_text='상위 권위. 예: Cambrian Subcommission → ICS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chrono.authority')),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoundaryLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('created', 'created'), ('renamed', 'renamed'), ('split', 'split'), ('merged', 'merged'), ('retyped', 'retyped (GSSA↔GSSP)'), ('deprecated', 'deprecated')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage', to='chrono.boundary')),
                ('sources', models.ManyToManyField(blank=True, help_text='split/merge 원본(들), rename 의 이전 경계', related_name='lineage_targets', to='chrono.boundary')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: "Meishan D, Changxing, Zhejiang, China"', max_length=300)),
                ('level', models.CharField(blank=True, help_text='예: "base of Bed 27c"', max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('boundary', models.OneToOneField(help_text='이 노두가 정의하는 경계(GSSP)', on_delete=django.db.models.deletion.CASCADE, related_name='stratotype', to='chrono.boundary')),
            ],
            options={
                'verbose_name_plural': 'localities',
            },
        ),
        migrations.CreateModel(
            name='Ratification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratifications', to='chrono.authority')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratifications', to='chrono.boundary')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='안정 식별자. 예: changhsingian', unique=True)),
                ('name', models.CharField(help_text='고유명(등급어 제외). 예: Changhsingian', max_length=100)),
                ('rank', models.IntegerField(choices=[(1, 'Eon / Eonothem'), (2, 'Era / Erathem'), (3, 'Period / System'), (4, 'Epoch / Series'), (5, 'Age / Stage')])),
                ('parent', models.ForeignKey(blank=True, help_text='상위 등급 단위. 예: Changhsingian(Age) → Lopingian(Epoch)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chrono.unit')),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='boundary',
            name='above',
            field=models.ForeignKey(blank=True, help_text='경계 위(더 젊은) 단위', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boundaries_below', to='chrono.unit'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='below',
            field=models.ForeignKey(blank=True, help_text='경계 아래(더 오래된) 단위', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boundaries_above', to='chrono.unit'),
        ),
    ]
