# Generated by Django 5.2.12 on 2026-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='color',
            field=models.CharField(blank=True, default='', help_text='ICS 공식 색 (#RRGGBB). ICC 차트 표시용.', max_length=7),
        ),
    ]
