# Generated by Django 5.2.12 on 2026-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0002_unit_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Eon / Eonothem'), (2, 'Era / Erathem'), (3, 'Period / System'), (4, 'Subperiod / Subsystem'), (5, 'Epoch / Series'), (6, 'Age / Stage')]),
        ),
    ]
