# Generated by Django 5.2.12 on 2026-07-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0003_alter_unit_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent authority. e.g. Cambrian Subcommission → ICS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chrono.authority'),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='above',
            field=models.ForeignKey(blank=True, help_text='Unit above (younger than) the boundary', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boundaries_below', to='chrono.unit'),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='below',
            field=models.ForeignKey(blank=True, help_text='Unit below (older than) the boundary', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boundaries_above', to='chrono.unit'),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='definition_type',
            field=models.CharField(blank=True, choices=[('GSSP', 'GSSP (point)'), ('GSSA', 'GSSA (decreed number)')], help_text='Current definition method. Per-version truth is the releases snapshot.', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='name',
            field=models.CharField(help_text='Human-readable name. e.g. Base of the Triassic', max_length=200),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='slug',
            field=models.SlugField(help_text='Stable slug. e.g. base-triassic', unique=True),
        ),
        migrations.AlterField(
            model_name='boundarylineage',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='split/merge origin(s), the previous boundary of a rename', related_name='lineage_targets', to='chrono.boundary'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='boundary',
            field=models.OneToOneField(help_text='The boundary this outcrop defines (GSSP)', on_delete=django.db.models.deletion.CASCADE, related_name='stratotype', to='chrono.boundary'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='level',
            field=models.CharField(blank=True, help_text='e.g. "base of Bed 27c"', max_length=300),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(help_text='e.g. "Meishan D, Changxing, Zhejiang, China"', max_length=300),
        ),
        migrations.AlterField(
            model_name='unit',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Official ICS color (#RRGGBB). For ICC chart display.', max_length=7),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Proper name (without the rank term). e.g. Changhsingian', max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Higher-rank unit. e.g. Changhsingian(Age) → Lopingian(Epoch)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chrono.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(help_text='Stable identifier. e.g. changhsingian', unique=True),
        ),
    ]
