# Generated by Django 5.2.12 on 2026-07-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='식별자 = engine 커널 바인딩 키. 예: age-depth-model', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('data', 'Data (불변 관측·leaf)'), ('process', 'Process (변환·모델)'), ('clamp', 'Clamp (거버넌스 게이트)')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('params_schema', models.JSONField(blank=True, default=dict, help_text='파라미터 스키마(JSON). 에디터가 파라미터 컨트롤을 렌더할 근거.')),
            ],
            options={
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('datatype', models.CharField(choices=[('distribution', 'distribution'), ('scalar', 'scalar'), ('series', 'series'), ('signal', 'signal'), ('any', 'any')], default='distribution', max_length=12)),
                ('multiple', models.BooleanField(default=False, help_text='다중 연결 허용(번들 입력)')),
                ('order', models.IntegerField(default=0)),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='nodes.nodetype')),
            ],
            options={
                'ordering': ['node_type', 'direction', 'order'],
                'constraints': [models.UniqueConstraint(fields=('node_type', 'direction', 'name'), name='uniq_port_per_direction')],
            },
        ),
    ]
