# Generated by Django 5.2.12 on 2026-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='category',
            field=models.CharField(choices=[('data', 'Data (immutable observation / leaf)'), ('process', 'Process (transform / model)'), ('clamp', 'Clamp (governance gate)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='params_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Parameter schema (JSON). Basis for the editor to render parameter controls.'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='slug',
            field=models.SlugField(help_text='Identifier = engine kernel binding key. e.g. age-depth-model', unique=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Allow multiple connections (bundle input)'),
        ),
    ]
