# Generated by Django 5.2.12 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_nodetype_category_alter_nodetype_params_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='category',
            field=models.CharField(choices=[('data', 'Data (immutable observation / leaf)'), ('process', 'Process (transform / model)'), ('clamp', 'Clamp (governance gate)'), ('reference', 'Reference (provenance / citation)')], max_length=10),
        ),
    ]
