# Generated by Django 5.2.12 on 2026-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_nodetype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='category',
            field=models.CharField(choices=[('data', 'Data (immutable observation / leaf)'), ('process', 'Process (transform / model)'), ('reference', 'Reference (provenance / citation)')], max_length=10),
        ),
    ]
