# Generated by Django 5.2.12 on 2026-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id / natural key. e.g. cohen-2013-ics', max_length=120, unique=True)),
                ('doi', models.CharField(blank=True, help_text='DOI without the https://doi.org/ prefix.', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, help_text='e.g. Cohen, Finney, Gibbard & Fan', max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('container', models.CharField(blank=True, help_text='Journal / publisher / venue.', max_length=300)),
                ('url', models.URLField(blank=True, help_text='Fallback link when there is no DOI.')),
                ('kind', models.CharField(choices=[('article', 'journal article'), ('book', 'book'), ('chapter', 'book chapter'), ('dataset', 'dataset'), ('report', 'report'), ('web', 'web')], default='article', max_length=10)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year', 'slug'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('doi', ''), _negated=True), fields=('doi',), name='uniq_doi_when_present')],
            },
        ),
    ]
