# Generated by Django 5.2.12 on 2026-07-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='{computed, cached} 등')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='graph.graph')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CoherenceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=True)),
                ('checks', models.JSONField(blank=True, default=dict, help_text='{L0, L1, L2, L3: pass|warn|skip}')),
                ('eval_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='engine.evalrun')),
            ],
        ),
        migrations.CreateModel(
            name='NodeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=40)),
                ('distribution', models.JSONField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=list)),
                ('cached', models.BooleanField(default=False, help_text='이전 run 에서 재사용(증분 히트)')),
                ('eval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='engine.evalrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('eval_run', 'node_key'), name='uniq_result_per_run_node')],
            },
        ),
    ]
