# Generated by Django 5.2.12 on 2026-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalrun',
            name='stats',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {computed, cached}'),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='cached',
            field=models.BooleanField(default=False, help_text='Reused from a previous run (incremental hit)'),
        ),
    ]
